apiVersion: v1
kind: Service
metadata:
  name: cakes
spec:
  selector:
    app: cakes
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cakes
  template:
    metadata:
      labels:
        app: cakes
    spec:
      containers:
      - name: cakes
        image: medek1/cakes
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
