apiVersion: v1
kind: Service
metadata:
  name: web-python
spec:
  type: LoadBalancer
  selector:
    app: web-python
  ports:
  - port: 7070
    targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-python
  template:
    metadata:
      labels:
        app: web-python
    spec:
      containers:
      - name: web-python
        image: olehmydynskyi/simple-python-app:nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 7070
